# Agustin Addon

version: '3.8'
services:
  db_usuarios:
    image: postgres:15
    container_name: postgres_usuarios_auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_usuarios
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: usuarios_auth_db
    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data

volumes:
  postgres_usuarios_data: